In [1]:
import numpy as np

In [14]:
arr1 = np.array([1,2,3,4,5], dtype='float')

In [17]:
print arr1
print arr1.nbytes
print arr1.dtype.itemsize

[ 1.  2.  3.  4.  5.]
40
8


In [24]:
np.linspace(1, 20, 10, dtype = 'float')

array([  1.        ,   3.11111111,   5.22222222,   7.33333333,
         9.44444444,  11.55555556,  13.66666667,  15.77777778,
        17.88888889,  20.        ])

In [31]:
a = np.arange(10, 100, 10)

In [27]:
np.logspace(10, 22, 8)

array([  1.00000000e+10,   5.17947468e+11,   2.68269580e+13,
         1.38949549e+15,   7.19685673e+16,   3.72759372e+18,
         1.93069773e+20,   1.00000000e+22])

In [30]:
import antigravity

In [39]:
b = a.reshape((3,3))
c = np.arange(10, 100, 10).reshape((3 , 3))

In [40]:
print a, b

[10 20 30 40 50 60 70 80 90] [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [46]:
arUnique = np.array([10,2,10,3,4,2])

In [47]:
arr3= np.unique(arUnique)

In [48]:
print arr3

[ 2  3  4 10]


In [52]:
# np.where почитать
import numpy as np

In [54]:
arrrayy = np.where(arUnique > 2)

In [56]:
print arrrayy

(array([0, 2, 3, 4], dtype=int64),)


In [57]:
indexx = (arUnique > 2)

In [58]:
print indexx

[ True False  True  True  True False]


In [59]:
print arUnique[indexx]

[10 10  3  4]


In [60]:
import scipy